complete the interface
Tommy-Zhang3759/Sysync-ConfigServer pull request #8
Opened 2024-09-24 16:07 UTC by PelerYuan

2024-09-25 14:22 UTC, Tommy-Zhang3759 requested changes
calm down~ if you don't want, no need to spend time. just~ be~ happy~~~

2024-09-25 14:22 UTC, Tommy-Zhang3759 commented on utils/dataFrame.go
> +		if c.csvData[index][index] == key {
do you mean csvData[Rawindex][index]? by the way, row, instead of "raw" maybe.

2024-09-25 14:22 UTC, Tommy-Zhang3759 commented on utils/dataFrame.go
> +		if c.csvData[index][index] == key {
might same as the previous problem. [RawIndex][index] instead of [index][index]

2024-09-26 09:18 UTC, PelerYuan commented
apologize for disatraction...
I will rewrite all the code

2024-09-26 12:28 UTC, merged